### ISSUE TITLE
参考levedb实现Compaction多种触发策略

### ISSUE THREAD

**Issue by loloxwg** [KipData/KipDB#3]
- 现有策略根据数据条数进行触发Compaction判定
- 原有用数据量的bytes大小来判定
- 可以参考 levedb 实现多种触发策略同时存在

**Comment by KKould** [comment]
BenchMark中的测试受此影响：大KeyValue因为目前仅按条数进行Compaction，导致满内存而停止运行
![d01db873194af05d2c124f82b13f7f3](https://github.com/KipData/KipDB/assets/91525956/2b882563-f905-4fb5-a70e-219b66e9a6dd)
